### ISSUE TITLE
Validating results in white page with no info

### ISSUE THREAD

**Issue by nixer89** [rswarthout/payid-validator#1]
I am trying to validate:

donate$xumm.community

and

onemorehome$goodxrp.org

but the website just shows a white page.

But the PayIDs are working when accessing  via CURL or the PayID CORS example (website snipped)

**Comment by rswarthout** [comment]
Thank you for letting me know about this issue. It has been resolved in this commit. https://github.com/rswarthout/payid-validator/commit/ee8a686f93075df6da6542d8b1a5f96f4e7dc17f
