### ISSUE TITLE
Please check out 500 Server error on 200 OK response

### ISSUE THREAD

**Issue by kencarabello** [rswarthout/payid-validator#10]
Hello.

I rebuilt my server again. Proxy Good. SSL check on Qualsys site brings back an A rating. 
Curt POST to create goes through. Repeat curl POST says "User Already exists".
Curl GET request brings back a 200 OK. 
But on the validator, I get a 500 server error. I have no idea why.
Please assist. my payID is ken$payid.cloud ; XRP; MAINNET 
Thanks.

Ken

**Comment by rswarthout** [comment]
Hi Ken. What PayID are you trying?

**Comment by kencarabello** [comment]
Hi there.

ken$payId.cloud (XRPL MAINNET).

Thanks.

**Comment by rswarthout** [comment]
Ok, thanks. I will check this later when I am at my computer.

**Comment by kencarabello** [comment]
Thanks, RS!

**Comment by rswarthout** [comment]
Hi Ken. When I try ken$payid.cloud the validator is receiving a 502 back from your server. The validator has no way of knowing what is causing this error on your server's end of the request.

**Comment by kencarabello** [comment]
Okay. That is because the server is down right now. I will put it back up
in 30 min and leave it up for 24h. Please check again after an hour or so.

Thanks, Robert!

**Comment by kencarabello** [comment]
I'm trying to upgrade to 1.1
So far just Dockerfile, docker-compose.yml, and Package.json.

I'll leave it there til tomorrow. Server will be back up in 30.

Thanks!

**Comment by kencarabello** [comment]
Okay, Robert.

The server is back up on http://payid.cloud.

I won't touch it for 24 hours.

Thanks for the help.

Ken

**Comment by rswarthout** [comment]
Hi Ken. I just handled the case that did not allow the error to be presented to you on validation. Your addressDetails object is supposed to contain a property called "address" but your server is returning a property called "Address". Once you have this resolved it looks like you will validate at 100%.

**Comment by kencarabello** [comment]
Okay, I'm on it.
Thank you, Robert!

**Comment by kencarabello** [comment]
Holy Smoke!
It worked!
green and clean all the way down!
Great to see!
Thanks, again, sir!
