### ISSUE TITLE
Add ability to return defined PayID payloads with specific issues

### ISSUE THREAD

**Issue by rswarthout** [rswarthout/payid-validator#12]
**Is your feature request related to a problem? Please describe.**
This feature would allow developers integrating PayID into their applications to make requests to defined PayID addresses that have defined issues in the payload or headers. These addresses would be used in the development/testing flow. By offering these defined PayID address to problematic payload combinations it frees the developer to make sure their application is handling edge-cases they might not thought about.

**Describe the solution you'd like**
The suggested solution is to provide a list of different issues that could be returned and allow the developer to generate an address that fulfills that combination. A way to handle the endless combinations a user might choose, utilizing bitwise values could be a viable solution.

Example selections
* 1 - Missing payment network property
* 2 - Invalid Content-Type header value
* 4 - Invalid JSON
* 8 - Missing “payId” property in the root of the JSON object

The interface would generate the PayID address for the developer after the selected the desired issues. The generated PayID address would be `test-7$payidvalidator.com` if the user selected the first three options above with bitwise values of 1, 2, 4. If the user did not select any issues the address would just be `test$payidvalidator.com`.

**Describe alternatives you've considered**
An alternative to using bitwise would be to have a list of pre-defined PayID addresses with descriptions to describe the expected issues. A downside to using predefined PayID addresses is that there is no good way to combine multiple issues into a single request. The list of addresses would be quite extensive if combinations were provided.

Example addresses
* `test-missingpaymentnetwork$payidvalidator.com`
* `test-invalidcontenttype$payidvalidator.com`
* `test-invalidjson$payidvalidator.com`
* `test-missingpayidproperty$payidvalidator.com`

**Comment by 0xCLARITY** [comment]
> 8 - Missing “payId” property in the root of the JSON object

I believe that `payId` in the root of the JSON is an optional field right now. Still a best practice to include it, I think, but not strictly necessary.

It might be useful to distinguish between "Incompatible Issues" that would make it so a wallet probably couldn't understand responses from your PayID server, vs "Best Practices" that aren't strictly necessary, but are strong recommendations.

**Comment by rswarthout** [comment]
Good point @hbergren, I will take that into consideration.

**Comment by rswarthout** [comment]
This feature can be found at https://payidvalidator.com/payid-generator.php
