### ISSUE TITLE
Adjust Access-Control-Allow-Methods rule to WARN if DELETE, PATCH, POST, or PUT is listed 

### ISSUE THREAD

**Issue by rswarthout** [rswarthout/payid-validator#13]
**Describe the bug**
Is DELETE, PATCH, POST, or PUT is listed as a supported method in the Access-Control-Allow-Methods header it should be shown as a WARN level for the rule instead of PASS.

**To Reproduce**
Use the PayID address`xrptipbot$bithomp.com` and XRP (mainnet) as your validation combination. You will see that POST

**Expected behavior**
A public-facing PayID server should not contain anything in the Access-Control-Allow-Methods besides GET, OPTIONS.

**Comment by 0xCLARITY** [comment]
I think https://github.com/payid-org/payid currently has `GET, POST, OPTIONS` in the allowed methods, because we had been thinking that POST would be used for a flow not currently implemented, but I think `GET, OPTIONS` makes sense as that describes the current best practice.
