### ISSUE TITLE
PayID with capital letter fails format check

### ISSUE THREAD

**Issue by ysv** [rswarthout/payid-validator#16]
**Describe the bug**
By its design PayIDs are case insensitive which means that "ABCD$payid.com" == "abcd$payid.com" but validator says that PayID with a capital letter has invalid format.

![image](https://user-images.githubusercontent.com/19859122/99710768-a4f08d80-2aa9-11eb-8199-eb34de332e2e.png)

For us it's important to have PayIDs with capital letter to make them recognisable by our clients because the first part of PayID in our case is external user id.

**To Reproduce**
PayID address (any payid with capital letter): e.g. `IDAD45C02BE6$payid.test.coinselect.com`
Network (isn't important): e.g. xrpl-testnet

**Expected behavior**
Don't fail format validation for PayID with capital letter.

**Comment by rswarthout** [comment]
Thank you for reporting this issue, it has been fixed.
