### ISSUE TITLE
Insufficient "Response Body Addresses Match Requested Headers" check

### ISSUE THREAD

**Issue by 0xCLARITY** [rswarthout/payid-validator#2]
For an `All - application/payid+json` request, I would expect the returned `Content-Type: application/payid+json`.

However, even for a request with that response header, the "response body addresses match requested headers check" fails. We probably just need an exception to that rule for `application/payid+json`.

You can use `hbergren$xpring.money` to reproduce.

**Comment by rswarthout** [comment]
Thanks for pointing this out. It is resolved in commit https://github.com/rswarthout/payid-validator/commit/327855b26c4a5e0e6c252fa5bc6277d0952a9fb3.
