### ISSUE TITLE
ken$payID.cloud

### ISSUE THREAD

**Issue by kencarabello** [rswarthout/payid-validator#5]
Hi, there.

I get a 500 error when I try to validate this payID on Ripple MAINNET.
Can you please advise? I built the server and database on AWS. All SEEMS okay.
Would just like to be sure.

Thanks

Ken
Discord: KenPayID

**Comment by rswarthout** [comment]
Hi. 

It doesn't look like you are hosting that over HTTPS. I can load your site just fine via HTTP but when I do an HTTPS request it fails with an SSL error. All PayID requests are made over HTTPS, TLS1.2+.

I will work to handle this error better and present it to the user.

**Comment by rswarthout** [comment]
The connect errors are now shown to the user when a failure occurs as connect time.

**Comment by kencarabello** [comment]
Hi there.

Okay great. Thanks. My 443 is open. But I made the create payID ( curl
POST) on http. That is what is in the guide. So do I need to create again?
Or just handle th GET on 443? If so, do I need a certbot certificate just
to confirm the payID record (curl GET) ? Please advise.

Thanks.

Ken.

**Comment by kencarabello** [comment]
I just ran the curl POST on https. Got unknown protocol error. Looks like a
Certbot thing. Please confirm.

Thanks.

**Comment by rswarthout** [comment]
@kencarabello You will need to get HTTPS hosting working. You can confirm it is working by being able to load your website in a browser via [https://payid.cloud](https://payid.cloud). Once you can load your website in the browser via HTTPS, you can run a check at [payidvalidator.com](https://payidvalidator.com) to see if the PayID data is being returned correctly.

**Comment by kencarabello** [comment]
Awesome!
Thanks, Robert!
