### ISSUE TITLE
500 error for PayID input

### ISSUE THREAD

**Issue by mrosendin** [rswarthout/payid-validator#6]
Thanks for your work on this project. I'm having trouble validating `matt$pay.identipay.net`. It's resulting in the 500 error page.

**Comment by rswarthout** [comment]
Thank you for reporting this issue. I have fixed the issue causing the 500 error. The default CA chain file included in Amazon Linux 2 (which this is hosted on) could not verify the SSL cert you are using on your site. I have disabled certificate verification, at least for the time being, until I can find a more graceful way to handle this and present it to the user.
